In [1]:
#tensors in pytorch
#source: https://pytorch.org/tutorials/beginner/basics/tensor_tutorial.html

In [2]:
import torch
import numpy as np

In [3]:
#tensors can be initialized in various ways:

#directly from data, the type is automatically inferred
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
#from a numpy array
#see Bridge with NumPy
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
#and even from another tensor
x_ones = torch.ones_like(x_data) #retains the properties of x_data. creates a tensor of the same dimensions (as well as other things?) as x_data, filled with ones
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) #overrides datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3153, 0.5670],
        [0.4397, 0.8878]]) 



In [6]:
#shape is a tuple of tensor dimensions, it determines the dimensionality of the output tensor
shape = (2, 3, )

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Shape: \n {shape} \n")
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Shape: 
 (2, 3) 

Random Tensor: 
 tensor([[0.7294, 0.6250, 0.8349],
        [0.4181, 0.3395, 0.2908]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [7]:
#attribues determine the shape, datatype, and device upon which a tensor is stored
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [8]:
#to move a tensor we need to use the to method (after checking for availability)
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [9]:
#standard numpy-like indexing and slicing
tensor = torch.ones(4, 4)

print("First row: ", tensor[0])
print("First Column: ", tensor[:, 0])
print("Last Column: ", tensor[..., -1])

tensor[:, 1] = 0
print(tensor)

#the ellipses is used to omit dimensions (for instance if you only wanted the first and last dimension, or grab all dimensions [like : if used with no other dimensions])
print("Elipsis constant:", ...)

First row:  tensor([1., 1., 1., 1.])
First Column:  tensor([1., 1., 1., 1.])
Last Column:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
Elipsis constant: Ellipsis


In [10]:
#you can concatenate a sequencse of tensors along a dimension using torch.cat
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(f"t1:: \n {t1} \n")

# you can also use torch.stack which is subtly different: it concatenates in a NEW dimension

t1:: 
 tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]]) 



In [11]:
#arithmetic operations

#computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
#operator syntax
y1 = tensor @ tensor.T
#method syntax
y2 = tensor.matmul(tensor.T)
#static(?) method syntax
y3 = torch.rand_like(tensor.T)
torch.matmul(tensor, tensor.T, out=y3)

#computes teh element-wise product, z1, z3, and z4 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [12]:
#if you have a one element tensor, for example by aggregating all values in a tensor to one value, you can convert it to a python numerical using item()
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [13]:
#in place operations are denoted by a _ suffix. x.copy_(y) and x.t_() will change x
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [14]:
#bridge with NumPy
#tensors on the CPU and NumPy arrays can share their underlying memory locations and changing one will change the other

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [15]:
#a change in the tensor reflects the numpy array
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [16]:
#and vice versa
n = np.ones(5)
t = torch.from_numpy(n)

print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]


In [17]:
np.add(n, 1, out=n)

print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
